site_name: 'Documentation'
site_description: 'A powerful Python package for geospatial data analysis and processing'
site_author: 'Utku Can Ozturk'

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  logo: assets/logo.png
  favicon: assets/GIGA_horizontal_notext_white.webp
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

repo_name: giga-spatial
site_url: https://unicef.github.io/giga-spatial
repo_url: https://github.com/unicef/giga-spatial
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - User Guide:
    - Overview: user-guide/index.md
    #- Basic Usage: user-guide/basic-usage.md
    #- Advanced Features: user-guide/advanced-features.md
    #- Best Practices: user-guide/best-practices.md
  - API Reference:
    - Overview: api/index.md
    - Handlers: api/handlers.md
    - Processing: api/processing.md
    - Core: api/core.md
    - Generators: api/generators.md
    - Grid: api/grid.md
    #- Core Functions: api/core.md
    #- Utilities: api/utils.md
    #- Data Types: api/data-types.md
  - Examples:
    - Overview: examples/index.md
  - Contributing:
    - How to Contribute: contributing.md
    #- Development Setup: contributing/development-setup.md
    #- Code Style Guide: contributing/code-style.md
  - About:
    - Changelog: changelog.md
    - License: license.md
    #- Credits: credits.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.snippets
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_submodules: true
          filters:
              - "!^_" 
          rendering:
            show_source: true
            show_category_heading: true
            show_root_heading: true
            show_signature_annotations: true
  #- git-revision-date-localized:
  #    enable_creation_date: true
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        background_color: blue
        color: white

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/unicef/giga-spatial
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/giga-spatial/
  version:
    provider: mike
  
  generator: false

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 Giga